name: Deploy Toyobi Field

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Runs at the top of every hour

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # repo root, contains index.html
          user_name: 'Toyobi AI'
          user_email: 'toyobi@example.com'

      # 3️⃣ Optional: Status log
      - name: Log deployment
        run: echo "Toyobi field deployed at $(date)"
